### ISSUE TITLE
An error was reported when I cross compiled ARM

### ISSUE THREAD

**Issue by JAVIERCUADROS7** [gen2brain/shm#2]
When I try to cross compile I get this ......

github.com/gen2brain/shm
../../../../go/pkg/mod/github.com/gen2brain/shm@v0.0.0-20191025110947-b09d223a76f1/shm.go:64:34: undefined: sysShmGet
../../../../go/pkg/mod/github.com/gen2brain/shm@v0.0.0-20191025110947-b09d223a76f1/shm.go:76:36: undefined: sysShmAt
../../../../go/pkg/mod/github.com/gen2brain/shm@v0.0.0-20191025110947-b09d223a76f1/shm.go:100:38: undefined: sysShmDt
../../../../go/pkg/mod/github.com/gen2brain/shm@v0.0.0-20191025110947-b09d223a76f1/shm.go:111:35: undefined: IdDs
../../../../go/pkg/mod/github.com/gen2brain/shm@v0.0.0-20191025110947-b09d223a76f1/shm.go:112:38: undefined: sysShmCtl
../../../../go/pkg/mod/github.com/gen2brain/shm@v0.0.0-20191025110947-b09d223a76f1/shm.go:128:11: undefined: IdDs

**Comment by gen2brain** [comment]
Support for arm/arm64 is added in https://github.com/gen2brain/shm/commit/49f9650110c5a40d305291f0ce0807712c06a81e . Please check now.
